web:
 image: nginx:latest
 container_name: desafio
 restart: always
 ports:
  - "8080:80"
 volumes: 
  - ./app:/usr/share/nginx/html
 links:
 - php
php:
 image: php:7.3-fpm
 container_name: php-fpm
 volumes:
 - ./app:/usr/share/nginx/html
 